services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    #    user: 1000:1000
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - VERSION=docker
      - PLEX_CLAIM=$PLEX_CLAIM
    volumes:
      #      - /docker/appdata/plexpass:/config
      - /mnt/v1/apps/plex:/config
      - /mnt/v1/media/videos/tvshows:/tv
      - /mnt/v1/media/videos/movies:/movies
      - /mnt/v1/media/homevideos:/homevideos
      - /mnt/v1/media/music:/music
      - /mnt/v1/media/photos:/photos
      - /mnt/v1/media/slideshow:/slideshow
    restart: unless-stopped
    env_file: .env
networks: {}
